HW_2
ostapchug/taras-ostapchuk pull request #2
Opened 2022-06-25 17:01 UTC by ostapchug

2022-07-11 18:05 UTC, KostyantynPanchenko requested changes
Потребує доопрацювання

2022-07-11 18:05 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework2/Application.java
> +            System.out.println(applicationContext.getBean(myBeanName));
Правильне виконання пунку 12:
`System.out.println(context.getBeanDefinition(beanName));`

2022-07-11 18:05 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework2/beans/BeanA.java
> +    public void validate() {
Валідації не місце у цьому класі

2022-07-11 18:05 UTC, KostyantynPanchenko commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
Завдання не передбачає використання SpringBoot

2022-07-11 18:05 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework2/config/BeansConfig.java
> +    @ConfigurationProperties(prefix = "bean-b")
`@ConfigurationProperties` - фіча SpringBoot.
Як зробити без нього?

2022-07-11 18:07 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework2/Application.java
> +        ApplicationContext applicationContext = SpringApplication.run(Application.class, args);
Контекст потрібно закривати

2022-07-12 09:23 UTC, KostyantynPanchenko requested changes

2022-07-12 09:23 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework2/Application.java
> +            System.out.println(applicationContext.getBeanDefinition(beanName));
Думка вголос: можна було б добавити і в попередній цикл.

2022-07-12 09:35 UTC, ostapchug commented on src/main/java/com/epam/spring/homework2/beans/AbstractBean.java
> +public abstract class AbstractBean {
щоб задати поведінку класам нащадкам і інстанс мені його не потрібний

2022-07-12 09:40 UTC, ostapchug commented on src/main/java/com/epam/spring/homework2/Application.java
> +            System.out.println(applicationContext.getBeanDefinition(beanName));
хотів щоб назви і опис бінів виводились окремо

2022-07-12 13:39 UTC, KostyantynPanchenko approved these changes

2022-07-12 17:01 UTC, closed without merging